server:
  #ip: 139.196.123.157
  ip: localhost
  port: 8895

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/springboot-vueno3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://139.196.123.157:3306/springboot-vueno3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 333
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: html
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


files:
  upload:
    path: D:/JAVA/springboot-vue第三项目工作空间30小时/myspringboot/src/main/resources/static/files/
#    path: /home/files/